[package]
name = "viewer"
version = "0.1.0"
edition = "2021"


[dependencies]
bevy_ecs = "0.10.1"
dyn-clone = "1.0.11"
lazy_static = "1.4.0"
wgpu = "0.16.0"
env_logger = "0.10.0"
mylib = {path ="../../lib/mylib"}

